import '../styles/globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={'h-full w-full'}>
			<body
				className={
					'font-Elice font-medium h-full w-full bg-primary-navy-3'
				}
			>
				<div id={'portal'}></div>
				{children}
			</body>
		</html>
	);
}
